apiVersion: velero.io/v1
kind: Backup
metadata:
  name: nginx-stateless
  labels:
    velero.io/storage-location: default
  namespace: oadp-operator-system
spec:
  hooks: {}
  includedNamespaces:
  - nginx-example
  storageLocation: example-velero-1
  ttl: 720h0m0s
