apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mssql-persistent
  labels:
    velero.io/storage-location: default
  namespace: oadp-operator-system
spec:
  hooks: {}
  includedNamespaces:
  - mssql-persistent
  storageLocation: default
  ttl: 720h0m0s
